# Generated by Django 4.2.6 on 2024-02-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_appsetting_trainer_trainernotification_notify_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='pwd',
            new_name='password',
        ),
    ]
